### ISSUE TITLE
MongoSessionHelpers.cs file is added when installing nuget package

### ISSUE THREAD

**Issue by judowalker** [MarkCBB/MongoDB-ASP.NET-Session-State-Store#6]
The `MongoSessionHelpers.cs` file is being added to my project when I install the nuget package. This should be part of the MongoSessionStateStore assembly.

**Comment by MarkCBB** [comment]
I'm starting with the changes to include this class in the assembly instead to include it in a source file.

The current situation is:

This class was included in a provided file to enable users of this package to personalize the code if needed. Note that the classes inside the provided file are static classes and can't be extended in the destination solutions.

The reasons to be an static class are:
- **Is the only way to implement static extensions** that provides a clean implementation.
- **We need only one instance of these implementations**, their methods are thread safe.

The challenge Including the file in the assembly is to maintain the capability of personalization and maintain these helpers as static extensions. By this, also will be possible to deploy a new version without requiring changes in the code for current deployments.

Taking into account this specs I'm moving to the following solution:
- Include the static class with the extensions into the assembly.
- The current implementations in the static class will be moved to another public class that will be extended from a public interface.
- The static class only will have a reference to this interface.
- The reference to this interface will be initialized by default with an instance of the class that contains the current implementation. Only one instance is needed and only one instance will be loaded in memory.
- The provided class will have all implementations defined as virtual to enable partial personalization for some methods.
- For those users that wants to create it's own full implementation they will be able to extend this interface.
- In both cases, partial or completely new implementations, the users will be able to set their own instance with their implementations using a method in the static class. Will be strongly recommended to do it in the application start method. By this you ensure that the right implementation is set before the start of the application only once.

Doing that (pending to test and demonstrate) I'll provide:
- The same personalization capabilities.
- Same implementation of helpers.
- No changes needed in the code of the current implementations that are currently working with the helpers as is provided (in case of changes those changes must be moved).
- An optimal memory usage.

All of these changes must be documented before the new release. Of course, this is a major release because implies changes in the API. 

I'll update this conversation as I progress.

**Comment by judowalker** [comment]
Sounds great. Thanks.

**Comment by MarkCBB** [comment]
The development is nearly finished. This release will also include the solution for the issue #4  .
I expect to finish the documentation updates and to pass the latest test cases during the next week. Also, I will try to pass the test cases with latest mongoDB driver (version 2.2.3).
So, I estimate to release the new revision by next weekend.

**Comment by MarkCBB** [comment]
Planned to be solved in release v4.0.0.

**Comment by MarkCBB** [comment]
Change included in v4.0.0.
