### ISSUE TITLE
MongoDB User Permission Required

### ISSUE THREAD

**Issue by pravindwiwedi** [MarkCBB/MongoDB-ASP.NET-Session-State-Store#8]
I am using mongoDb "myUser" user with the roles-
{ role: "readWrite", db: "MyDB" }
It is not accepting and giving connections error.

But when I use mongoDb "myAdminUser" with the roles-
 { role: "userAdminAnyDatabase", db: "admin" } 
It gets connected without any problem.

We want to use "MyDB" database to store the session data. We do not want to use Admin user. So, could you please let me know what are the pre-requisite user privileges from MongoDB side in order to implement Session-State-Store tool?
MongoDB Version- 3.2

Regards
Pravin Dwiwedi

**Comment by MarkCBB** [comment]
Hello @pravindwiwedi 

Have you tried to disable the TTL index creation? Just set the parameter AutoCreateTTLIndex to false and try it again (the default value is true).

Please, let me know how it goes.

[Here](https://github.com/MarkCBB/MongoDB-ASP.NET-Session-State-Store/wiki/Web.config-parameters) you have an example of all web.config parameters.
And [here](https://github.com/MarkCBB/MongoDB-ASP.NET-Session-State-Store/wiki/Web.config-parameters#autocreatettlindex) an explanation about the parameter and what the TTL index does.

**Comment by MarkCBB** [comment]
The TTL index creation is the only command that the application sends to mongoDB that could need admin permissions. All other commands are data related, so it shouldn't need this level of permission.

If you connect to the database with a user that does not have admin level, disabling the flag to don't create the TTL index should be enough to don't get any error related with admin permissions.

Note well that you should create a TTL index manually in the session collection in order to clean the data or define some external process to do it.

As I don’t have additional feedback, that would be nice to have, I understand that everything is working as expected. So, I’m going to close this issue.
